server:
  port: 8001
spring:
  application:
    name: signup-nacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8747
      discovery:
        username: nacos
        password: nacos
        namespace: public

