server:
  port: 8000
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    initialization-mode=always:
    url: jdbc:mysql://localhost:3306/mytestdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Register
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 550610344@qq.com #发送邮件的邮箱地址
    password:  jcgmokbjdqqmbcfc #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 550610344@qq.com # 发送邮件的地址，和上面username一致可以任意
    protocol: smtps
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8
